### ISSUE TITLE
Build instructions for linux are missing

### ISSUE THREAD

**Issue by jk-1** [oott123/tdlib-json-cli#1]
Please add build instructions for linux (ubuntu). Thanks.

**Comment by oott123** [comment]
See [td/README.md](https://github.com/tdlib/td/tree/6c706f45e7a73c936b9f2f267785092c8a73348f)

**Comment by jk-1** [comment]
Thanks. 
On this page: https://github.com/oott123/tdlib-json-cli   readme.md points nowhere.

**Comment by oott123** [comment]
I do know, but i think people can find it out by themselves, i'm too lazy to fix that :)
