### ISSUE TITLE
One problem in latest TdLib, i think.

### ISSUE THREAD

**Issue by prtngn** [oott123/tdlib-json-cli#15]
I encountered a problem that the generation of types.json is no longer working entirely correctly. For some reason, doxygen does not generate the `classtd_1_1td__api_1_1tdlib_parameters.html` file in the `td/docs/html` folder. Accordingly, this object does not appear in types.json. What do you think if I change the types.json generator to generate it from the tdlib website?

Generation takes longer, but there will always be up-to-date types.json. And at the same time, I wanted to add the root TlObject, TlFunction and, accordingly, all other methods and functions in types.json to inherit from these objects. The extends field will also change. For example, vectorPathCommandCubicBezierCurve will have VectorPathCommand in its extends. VectorPathCommand has extends Object. And Object has extends TlObject.

Is there anything else worth considering?

**Comment by oott123** [comment]
That's weird, I think source code are always up to date, at least than website. Maybe some dependencies are missing?

**Comment by prtngn** [comment]
Strange situation. In the nightly tdlib assembly, I don’t see the tdlibParameters object in the td_api.h header file. And I don’t see information in the changelog that the object was deleted.

**Comment by prtngn** [comment]
Yes, the problem turns out to be that the library for elixir has not been updated for a long time. It turns out tdlibParameters was renamed to SetTdlibParameters.
