### ISSUE TITLE
Type file generation fails

### ISSUE THREAD

**Issue by jk-1** [oott123/tdlib-json-cli#2]
OS is Ubuntu 16.04

File locations:

	tdlib dir = /home/jk/Downloads/tdlib-json-cli-master-2
	td dir = /home/jk/Downloads/td-master

Copy /home/jk/Downloads/td-master/* into /home/jk/Downloads/tdlib-json-cli-master-2/td

	cd /home/jk/Downloads/tdlib-json-cli-master-2
	mkdir Release
	cd Release
	cmake -DCMAKE_BUILD_TYPE=Release ..
	cmake --build .
	...
	[100%] Built target bench_tddb

Build seems to success fine.

Type file generation fails:

	cd /home/jk/Downloads/tdlib-json-cli-master-2/td

	doxygen
	...
	writing tag file...
	lookup cache used 12274/65536 hits=1555381 misses=13959
	finished...

	cd ../types-generator

	npm i
	types-generator@1.0.0 /home/jk/Downloads/tdlib-json-cli-master-2/types-generator
	└── html-entities@1.2.1 

	npm WARN types-generator@1.0.0 No description
	npm WARN types-generator@1.0.0 No repository field.
	npm WARN types-generator@1.0.0 license should be a valid SPDX license expression

	nodejs ./types-generator/index.js
	/home/jk/Downloads/tdlib-json-cli-master-2/types-generator/index.js:9
	;(async function () {
        	^^^^^^^^
	
	SyntaxError: Unexpected token function
    	at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:374:25)
    	at Object.Module._extensions..js (module.js:417:10)
	    at Module.load (module.js:344:32)
	    at Function.Module._load (module.js:301:12)
	    at Function.Module.runMain (module.js:442:10)
	    at startup (node.js:136:18)
	    at node.js:966:3

How can I fix this?

Thank you for your support.

**Comment by oott123** [comment]
Get a latest nodejs.
